services:
  mousefighter.server:
    image: ${DOCKER_REGISTRY-}mousefighterserver
    build:
      context: .
      dockerfile: MouseFighter.Server/Dockerfile
    networks:
      - mouse-traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`proto.mousefighter.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.middlewares.api_compress.compress=true"
      - "traefik.http.routers.api.middlewares=api_compress"

networks:
  mouse-traefik:
    external: true