name: main

on:
  push:
    branches:
    - master
  
jobs:        
    
  main:
    runs-on: ubuntu-latest
    
    steps:

    - name: deploy webapp
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          git -C MouseFighter pull
          docker compose -f MouseFighter/docker-compose.yml up --build -d